[book]
authors = ["James"]
language = "en"
multilingual = false
src = "src"
title = "Economics AQA Notes"

[output.html]
site-url = "economics-notes"
fold.enable = true
mathjax-support = true
git-repository-url = "https://github.com/tyhdefu/economics-notes"
